#cmsRun run_simulation_step1_2016.py CT_def
cmsRun run_simulation_step2_gainOption2_2016.py gainOption2
cmsRun run_simulation_step3_gainOption2_2016.py gainOption2
cmsRun trackCluster_test.py  gainOption2step3.root

