#cmsRun run_simulation_step1_2016.py CT_def
cmsRun run_simulation_step2_GainOptionNoise_PropagationTest_2016.py gainOptionNoiseTest2
cmsRun run_simulation_step3_2016.py gainOptionNoiseTest2
cmsRun trackCluster_test.py  gainOptionNoiseTest2step3.root

cmsRun run_simulation_step2_GainOptionNoise_PropagationTest_2016.py gainOptionNoiseTest23
cmsRun run_simulation_step3_GainOptionNoise_PropagationTest_2016.py gainOptionNoiseTest23
cmsRun trackCluster_test.py  gainOptionNoiseTest23step3.root

